sample.data<- CreateSeuratObject(counts = sample.data, project = "your_project", min.cells = 3, min.features = 200)
sample.data[["percent.mt"]] <- PercentageFeatureSet(sample.data, pattern = "^mt-")
sample.data <- subset(sample.data, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 1.0)
sample.data.genes<-rownames(sample.data)
sample.data<-NormalizeData(sample.data)
sample.data<- FindVariableFeatures(sample.data, selection.method = "vst", nfeatures = 2000)
sample.data<-ScaleData(sample.data, features = sample.data.genes)
sample.data<-RunPCA(sample.data, features = VariableFeatures(sample.data))
sample.data<- JackStraw(sample.data, num.replicate = 100, dims = 50)
sample.data<- ScoreJackStraw(sample.data, dims = 1:50)
JackStrawPlot(sample.data, dims = 1:50)
